### ISSUE TITLE
PSR-4 Namespace İsimlendirme Problemi

### ISSUE THREAD

**Issue by volkanmetin** [yvolkan/api-provider#2]
Paket psr-4 standartlarına uygun bir namespace isimlendirmesi kullanmıyor. Bunu değiştirmemiz gerekmez mi?

**Comment by volkanmetin** [comment]
`yvolkan\ApiProvider` yerine `YVolkan\ApiProvider` kullanılması daha doğru geliyor.

**Comment by yvolkan** [comment]
Ben bu kullanımı nickname ile bağdaştırarak küçük olur diye düşünmüştüm. Detaylı araştırınca haklı olduğunuz kanısındayım.
